# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  virtualassistantapi:
    image: virtualassistantapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5206:5206
